name: Run Jest Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.15.0

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test
